pheno_name_key=c("Flowering Time" = "FLoweringtime",
                 "Greenhouse Damage" = "GHD",
                 "Plant Height (log)" = "Log_2019.2020_PH",
                 "AC1 (log)" = "Log_D1_2019.2020AC",
                 "D1 (log)" = "Log_D1_2019.2020",
                 "AC2 (log)" = "Log_D2_2019.2020AC",
                 "D2 (log)" = "Log_D2_2019.2020",
                 "NDRE" = "NDREAug25",
                 "NDVI" = "NDVIAug25",
                 "SAVI" = "SAVI_Aug25",
                 "NDRE (flowering covariate)" = "NDREAug25.with_flowering",
                 "NDVI (flowering covariate)" = "NDVIAug25.with_flowering",
                 "SAVI (flowering covariate)" = "SAVI_Aug25.with_flowering")